[Global]
# Supported operations are: all, inventory, process_monitor, cve
# - all: All operations are started by the monitor
# - inventory: Periodically scans the FS for specific product instances
# - process_monitor: Monitor for specific product process instances (uses WMI)
# - cve: Monitor for specific product instance vulnerabilities (periodic scans)
ActiveOperation = all

# Identifies with products should be monitored. For multiple products use comma to separate them,
# NOTE: For now, only Java is supported.
MonitorProducts = Java

# Location in the Windows registry to look for the active configuration
ConfigurationKey = HKEY_LOCAL_MACHINE\SOFTWARE\JGComplianceMonitor\ConfigLocation

# Configuration Flags
FLagInventoryScan = Yes
FlagProcessScan = Deactivated
FlagCVEScan = Deactivated

[Security]
